function [Xhat] = GSM_denoise(Y, gsm, noise)
% Denoises every column in Y, assuming a GSM model and white noise.
% 
% The model assumes that y = x + noise where x is generated by a mixture of
% 0-mean gaussian components sharing the same covariance up to a
% scaling factor
%
% Arguments
%  Y - A DxM matrix, whose every column corresponds to a patch in D
%      dimensions (typically D=64).
%  gsm - a struct with 3 fields:
%           mix - Mixture proportions.
%           covs - A DxDxK array, whose every page is a scaled covariance
%                  matrix according to scaling parameters.
%           means - K 0-means.
%  noise - the std of the noise in Y.
%

Xhat = GMM_denoise(Y, gsm, noise);