function [Xhat] = ICA_denoise(Y, ica, noise)
% Denoises every column in y, assuming an ICA model and white noise.
% 
% The model assumes that y = x + noise where x is generated by a ICA
% 0-mean mixture model.
%
% Arguments
%  Y - A DxM matrix, whose every column corresponds to a patch in D
%      dimensions (typically D=64).
%  ica - A struct with fields:
%           P - mixing matrix of sources (P: D ind. sources -> D signals)
%           vars - a DxK matrix whose (d,k) element correponsds to the
%                  variance of the k'th component in dimension d.
%           mix - a DxK matrix whose (d,k) element correponsds to the
%                 mixing weight of the k'th component in dimension d.
%  noise - the std of the noise in Y.
%

[D, K] = size(ica.mix);
SY = ica.P \ Y;

Shat = zeros(size(Y));
for i=1:D
    SY_i = SY(i,:);
    theta_i.means = zeros(K, 1);
    theta_i.covs = reshape(ica.vars(i,:), 1, 1, K);
    theta_i.mix = ica.mix(i,:)';
    Shat(i,:) = GMM_denoise(SY_i, theta_i, noise);
end

Xhat = ica.P * Shat;